# Generated by Django 4.1.7 on 2023-04-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cusine',
            new_name='cuisine',
        ),
    ]
